### ISSUE TITLE
Error when setting away mode

### ISSUE THREAD

**Issue by tigrrr** [signalkraft/mypyllant-component#131]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Using version [v0.7.4b9]
When setting away mode, the error below appears. The default temperature setpoint and all other settings in the integration configuration options are set, but the error persists.

### Logs

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:23:11 AM (1 occurrences)
Last logged: 11:23:11 AM

[140224036672704] setpoint is required on this controller
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/switch.py", line 62, in async_turn_on
    await self.coordinator.api.set_holiday(self.system, end=end)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 765, in set_holiday
    raise ValueError("setpoint is required on this controller")
ValueError: setpoint is required on this controller
```

**Comment by signalkraft** [comment]
Please try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b10 which should use the configured default temperature from the options.

**Comment by strizzi75** [comment]
Is there an option to set the default "away" temperature un the myVaillant app? I did not find an option, but if I start the away mode I cal set the temperature. Would be great if this would aslso be possiblem in the integration.

**Comment by boelle** [comment]
@tigrrr is this still an issue?

**Comment by tigrrr** [comment]
@boelle no, the issue was resolved, thanks for reminding.

**Comment by boelle** [comment]
btw... i'm just trying to help @signalkraft getting the list shorter with only problems still present
